import type { DomainId } from "./types";

export interface Flashcard {
  id: string;
  front: string;
  back: string;
  domainId: DomainId;
  tags: string[];
}

export const flashcards: Flashcard[] = [
  {
    id: "fc-agentic-loop",
    front: "What ends an agentic loop normally?",
    back: "Claude returns stop_reason end_turn — no tool_use blocks in the response. Turn budgets are only the safety net.",
    domainId: "agentic-architecture",
    tags: ["agentic loop"],
  },
  {
    id: "fc-orphan-results",
    front: "Agent re-calls a tool and answers from stale data — classic cause?",
    back: "Tool results were never appended back to the conversation as tool_result blocks, so Claude guesses.",
    domainId: "agentic-architecture",
    tags: ["agentic loop", "debugging"],
  },
  {
    id: "fc-workflow-vs-agent",
    front: "Workflow vs agent — when do you choose which?",
    back: "Workflows for predictable, well-understood steps (orchestrated code paths). Agents for open-ended problems where the path can't be known in advance.",
    domainId: "agentic-architecture",
    tags: ["workflows vs agents"],
  },
  {
    id: "fc-subagent-context",
    front: "What passes between orchestrator and subagent?",
    back: "A focused brief in; structured findings with provenance out — not full transcripts. Transcripts are debugging artifacts, not contracts.",
    domainId: "agentic-architecture",
    tags: ["subagents"],
  },
  {
    id: "fc-hil-gates",
    front: "How should human-in-the-loop gates be chosen?",
    back: "Structurally and programmatically: by action class (irreversible?), thresholds ($ amount), and scope — never by uncalibrated model self-confidence.",
    domainId: "agentic-architecture",
    tags: ["human-in-the-loop"],
  },
  {
    id: "fc-fanout-fanin",
    front: "Four independent vendor lookups then one synthesis — what pattern?",
    back: "Fan-out/fan-in: dispatch independent work in parallel, serialize the dependent join. Parallelize independence; synchronize dependencies.",
    domainId: "agentic-architecture",
    tags: ["orchestration", "parallel agents"],
  },
  {
    id: "fc-turn-budget",
    front: "Purpose of a turn budget?",
    back: "Bound worst-case cost and latency when stop conditions fail — converts runaway loops into bounded incidents.",
    domainId: "agentic-architecture",
    tags: ["budgets"],
  },
  {
    id: "fc-tool-description",
    front: "Where does most tool-selection quality come from?",
    back: "The tool description: what it does, when to use it, when NOT to use it, parameter meanings, return shape. It's the model's documentation.",
    domainId: "tool-design-mcp",
    tags: ["tool design"],
  },
  {
    id: "fc-error-categories",
    front: "Three canonical tool error categories?",
    back: "Transient (backoff + retry), validation (return to model for correction), permission (stop + escalate to human). Each gets different handling.",
    domainId: "tool-design-mcp",
    tags: ["failure handling"],
  },
  {
    id: "fc-empty-vs-error",
    front: "Tool finds no rows — empty array or error?",
    back: "Empty result. Errors are for execution failures; absence is valid data. Erroring forces pointless retries and masks real faults.",
    domainId: "tool-design-mcp",
    tags: ["structured errors"],
  },
  {
    id: "fc-idempotency",
    front: "Retried create_payment double-charged — missing mechanism?",
    back: "Idempotency keys on mutating tools: upstream deduplicates by key, making ambiguous timeouts safe to retry.",
    domainId: "tool-design-mcp",
    tags: ["idempotency", "retries"],
  },
  {
    id: "fc-token-cost-tools",
    front: "80 always-on tools: what two taxes do you pay?",
    back: "Token cost of 80 schemas on every request, plus attention competition during selection. Fix: consolidate + load tool groups per task.",
    domainId: "tool-design-mcp",
    tags: ["context windows", "tool design"],
  },
  {
    id: "fc-mcp-triangle",
    front: "MCP's three participants?",
    back: "Host (the app/LLM harness), Client (host's connector, one-to-one with a server), Server (exposes context via protocol). JSON-RPC is the wire format.",
    domainId: "tool-design-mcp",
    tags: ["mcp"],
  },
  {
    id: "fc-mcp-primitives",
    front: "Tools vs resources vs prompts in MCP?",
    back: "Tools = model-invoked actions. Resources = application-controlled read-only context. Prompts = reusable message templates.",
    domainId: "tool-design-mcp",
    tags: ["mcp"],
  },
  {
    id: "fc-mcp-auth",
    front: "Where do credentials live in an MCP integration?",
    back: "In infrastructure — per-user OAuth tokens scoped per capability, enforced server-side. Tokens never pass through model context.",
    domainId: "tool-design-mcp",
    tags: ["mcp", "authentication"],
  },
  {
    id: "fc-claudemd-hierarchy",
    front: "Monorepo CLAUDE.md layout?",
    back: "Thin root file for org-wide rules; one CLAUDE.md per package for local commands/conventions. Memory mirrors architecture.",
    domainId: "claude-code-workflows",
    tags: ["claudemd"],
  },
  {
    id: "fc-plan-mode",
    front: "When is Plan mode worth its ceremony?",
    back: "Ambiguous requirements or high blast radius (multi-file refactors, schema migrations). Not for small well-scoped fixes.",
    domainId: "claude-code-workflows",
    tags: ["plan mode"],
  },
  {
    id: "fc-hook-types",
    front: "PreToolUse vs PostToolUse hooks?",
    back: "PreToolUse validates/gates before execution. PostToolUse normalizes/augments results before the model sees them.",
    domainId: "claude-code-workflows",
    tags: ["hooks"],
  },
  {
    id: "fc-slash-json",
    front: "Team wants /security-review consumed by CI — setup?",
    back: "Custom slash command + claude -p --output-format json --json-schema. Commands standardize workflow; schemas standardize output.",
    domainId: "claude-code-workflows",
    tags: ["commands", "structured output"],
  },
  {
    id: "fc-headless-ci",
    front: "Which flags make Claude Code CI-friendly?",
    back: "-p/--print non-interactive mode, --output-format json, --json-schema for validated structure, --allowedTools for least privilege.",
    domainId: "claude-code-workflows",
    tags: ["ci/cd"],
  },
  {
    id: "fc-permission-boundary",
    front: "Enforce 'never touch prod files' how?",
    back: "Deny rules / PreToolUse hooks — programmatic enforcement at the boundary. Prompt instructions are advisory, not guarantees.",
    domainId: "claude-code-workflows",
    tags: ["permissions", "hooks"],
  },
  {
    id: "fc-schema-absence",
    front: "Field often absent but marked required — what happens?",
    back: "Fabrication (~9% invented dates in production examples). Fix: nullable fields + explicit instructions that unknown must be null.",
    domainId: "prompt-engineering",
    tags: ["json schema", "validation"],
  },
  {
    id: "fc-effective-retry",
    front: "What makes a retry effective?",
    back: "New information: append the validator's specific errors and the offending output so the attempt becomes guided repair, not a coin re-flip.",
    domainId: "prompt-engineering",
    tags: ["retries", "loops"],
  },
  {
    id: "fc-provenance-structure",
    front: "Prompt structure enabling citations?",
    back: "Tagged sections per document carrying metadata (URL, title, date); require citations referencing those tags. Provenance needs addressable origins.",
    domainId: "prompt-engineering",
    tags: ["provenance"],
  },
  {
    id: "fc-golden-evals",
    front: "Why gate prompt changes on a golden eval set?",
    back: "Silent regressions are invisible in diffs; frozen representative evals turn them into loud CI failures — regression insurance for prompts.",
    domainId: "prompt-engineering",
    tags: ["evaluation"],
  },
  {
    id: "fc-fewshot-purpose",
    front: "Few-shot examples primarily control…?",
    back: "Format and edge-case handling — they demonstrate ambiguity resolution better than any instruction. Quality beats quantity.",
    domainId: "prompt-engineering",
    tags: ["few-shot"],
  },
  {
    id: "fc-context-dilution",
    front: "150k-token session, model contradicts early commitments — why?",
    back: "Attention dilution: relevance signal decays as history grows. Fix: checkpoint-summarize resolved threads into durable state, resume compactly.",
    domainId: "context-reliability",
    tags: ["context windows", "summarization"],
  },
  {
    id: "fc-crash-resume",
    front: "Crash leaves corrupted span mid-history — resume policy?",
    back: "Validate, filter the corrupted span, compact, resume with provenance. Fresh start only if trust cannot be restored.",
    domainId: "context-reliability",
    tags: ["session management", "crash recovery"],
  },
  {
    id: "fc-error-as-data",
    front: "Ops + compliance both satisfied by which error design?",
    back: "Structured payloads: errorCategory drives handler branching; trace IDs give auditors attributable, queryable events.",
    domainId: "context-reliability",
    tags: ["error propagation", "observability"],
  },
  {
    id: "fc-minimum-instrumentation",
    front: "Minimum observability for inconsistent-answer diagnosis?",
    back: "Per-iteration traces: inputs, tool calls with args/results, outputs, token counts — correlated by session trace ID.",
    domainId: "context-reliability",
    tags: ["tracing"],
  },
  {
    id: "fc-exam-format",
    front: "CCA-F format essentials?",
    back: "60 items · 120 minutes · scaled pass mark 720 (100–1000) · $125 USD · proctored online via Pearson VUE · valid 12 months, free renewal.",
    domainId: "agentic-architecture",
    tags: ["exam facts"],
  },
  {
    id: "fc-domain-weights",
    front: "CCA-F domain weights (highest to lowest)?",
    back: "D1 Agentic Architecture 27% · D3 Claude Code Workflows 20% · D4 Prompt Engineering 20% · D2 Tool Design & MCP 18% · D5 Context & Reliability 15%.",
    domainId: "agentic-architecture",
    tags: ["exam facts"],
  },
  {
    id: "fc-workflow-pattern-list",
    front: "Name the five composable workflow patterns from Building Effective Agents.",
    back: "Prompt chaining · Routing · Parallelization (sectioning/voting) · Orchestrator-workers · Evaluator-optimizer. The autonomous agent is the sixth, non-workflow pattern where the model directs control flow.",
    domainId: "agentic-architecture",
    tags: ["workflows", "patterns"],
  },
  {
    id: "fc-mcp-client-primitives",
    front: "The three MCP server primitives — and who controls each?",
    back: "Tools = model-invoked actions · Resources = application-driven read-only context · Prompts = user-controlled templates. Clients expose elicitation (ask the user) and sampling (ask the host LLM).",
    domainId: "tool-design-mcp",
    tags: ["MCP", "primitives"],
  },
  {
    id: "fc-hooks-determinism",
    front: "CLAUDE.md rule vs hook — which one guarantees execution?",
    back: "Only hooks are deterministic. CLAUDE.md is advisory context loaded every session; hooks run scripts at lifecycle events regardless of model behavior.",
    domainId: "claude-code-workflows",
    tags: ["hooks", "CLAUDE.md"],
  },
  {
    id: "fc-evaluator-fit",
    front: "When does evaluator-optimizer add latency without quality?",
    back: "When criteria are vague or the evaluator is weaker than the generator on that criterion — the loop can't converge because the judge can't tell good from bad.",
    domainId: "prompt-engineering",
    tags: ["evaluator-optimizer", "loops"],
  },
  {
    id: "fc-tool-result-untrusted",
    front: "How should tool results be treated in injection defense?",
    back: "As untrusted data: JSON-encode third-party content, screen with a lightweight classifier, keep instructions out of tool_result blocks, gate risky actions behind confirmation.",
    domainId: "context-reliability",
    tags: ["prompt injection", "guardrails"],
  },
  {
    id: "fc-slash-command-invocation",
    front: "How are custom slash commands invoked in Claude Code?",
    back: "Users type /<command-name> during a session. The command is a prompt template stored in .claude/commands/, automatically expanded into the conversation. CI uses them via shell: claude -p '/my-command' --allowedTools.",
    domainId: "claude-code-workflows",
    tags: ["slash commands", "automation"],
  },
  {
    id: "fc-plan-mode-gate",
    front: "What is the key behavioral difference in plan mode?",
    back: "Claude thinks and proposes but never makes file changes or runs destructive commands until you approve. All tool_use is read-only by default — write operations require explicit user confirmation.",
    domainId: "claude-code-workflows",
    tags: ["plan mode", "permissions"],
  },
  {
    id: "fc-skill-lazy-loading",
    front: "Why do skills use lazy loading rather than always being in context?",
    back: "Skills are loaded on demand (when invoked via /skill-name) to keep the system prompt small. Loading every skill up-front wastes context tokens on irrelevant instructions and increases the chance of confusion.",
    domainId: "claude-code-workflows",
    tags: ["skills", "context management"],
  },
  {
    id: "fc-few-shot-position",
    front: "Where should few-shot examples go in a prompt for strongest effect?",
    back: "Immediately before the actual task input. Examples near the target are in the strongest attention zone. Distant examples in the middle of a long prompt have the weakest influence.",
    domainId: "prompt-engineering",
    tags: ["few-shot prompting", "attention placement"],
  },
  {
    id: "fc-structured-output-schema",
    front: "Why use JSON schema constraints on tool output vs free text?",
    back: "Schemas let you validate output programmatically. Claude conforms to the shape it sees; combined with retries for validation failures, you get reliable structured data without manual parsing.",
    domainId: "prompt-engineering",
    tags: ["structured output", "json schema"],
  },
  {
    id: "fc-checkpoint-compaction",
    front: "What is checkpoint compaction for context windows?",
    back: "When utilization exceeds ~85%, pause the loop, summarize the entire conversation into a compact checkpoint, drop the raw history, and resume with the summary. Gives 3-5x headroom at the cost of losing verbatim details.",
    domainId: "context-reliability",
    tags: ["context window", "compaction"],
  },
  {
    id: "fc-provenance-principle",
    front: "How should an agent preserve provenance across multi-step tool calls?",
    back: "Attach source identifiers to every finding. Each summary carries the evidence behind it — file path, line numbers, database row ID — so human reviewers can verify claims without replaying the entire session.",
    domainId: "context-reliability",
    tags: ["provenance", "observability"],
  },
];
